### ISSUE TITLE
Default RC filter settings

### ISSUE THREAD

**Issue by oh-ren** [digital-sound-antiques/in_msx#1]
I wonder why the default RC filter settings are the way they are (Resistance 4700 ohm, Capacitance 15 nF)? The result seems to be a way too muffled sound. AFAIC not that realistic(?) & might not make a good impression on new/unaware users?

I'm still experimenting though what the best values are. Lowering any of the 2 sounds like an improvement to me.. :) Do you have any recommendations for a clear & crisp (full) sound (but still perhaps with some realistic filter effect)?

edit - atm I've settled at _1300/12_, sounds 'crispy' (for SCC tunes anyway) :)

**Comment by okaxaki** [comment]
The default RC filter settings parameter I set 10 years ago is from the circuit example in the YM2413 data sheet. For more accuracy, RC filters for each devices are suitable but at that moment, I mainly focused on YM2413 sound and I worried about performance problem.

Anyway, time has changed. I'll think about the new filter implementation or default parameters.

**Comment by okaxaki** [comment]
The low-pass filter is disabled by default from [1.1.0](https://github.com/digital-sound-antiques/in_msx/releases/tag/1.1.0) so I close this issue.
