### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AntonZab** [digital-sound-antiques/in_msx#2]
Please build in_msx.dll

**Comment by okaxaki** [comment]
The latest binary is already available at https://github.com/digital-sound-antiques/in_msx/releases
If you have other trouble, let me know please.

**Comment by AntonZab** [comment]
Ok. Thanx

**Comment by AntonZab** [comment]
How about add moonblaster FM (mbf) or moonblaster wave (mwm) formats?

**Comment by okaxaki** [comment]
We currently have no plan to add new formats.
