### ISSUE TITLE
All songs in Winamp playlist does not show the total time

### ISSUE THREAD

**Issue by AntonZab** [digital-sound-antiques/in_msx#3]
In All songs in Winamp playlist does not show the total time

![4534](https://cloud.githubusercontent.com/assets/10308177/19964737/fcd693fa-a1dc-11e6-94ad-c69503f4f74e.JPG)

**Comment by okaxaki** [comment]
I edited the title of this issue so that people can guess content easier.

**Comment by okaxaki** [comment]
Currently this is a limitation of in_msx. KSS is not a pure audio format. It contains Z80 cpu executable code. in_msx emulates Z80 and execute the code in real-time while playing. There is no way to get
the song length before playing, and unfortunately, the most of songs are looped infinitely.
