### ISSUE TITLE
KSS module contains too many subsongs, why?

### ISSUE THREAD

**Issue by AntonZab** [digital-sound-antiques/in_msx#4]
Whi in this KSS module too many subsongs. And playing only 1?

https://drive.google.com/file/d/0B0oEDro3cJx-RmFHWFlSSXZ0OEk/view?usp=sharing

**Comment by okaxaki** [comment]
Every KSS file can contain 256 songs. Since the KSS format is very limited, there is no way to get the actual number of songs.

**Comment by okaxaki** [comment]
I modified the title of this issue so that people can guess content easier.
