### ISSUE TITLE
Subsongs error

### ISSUE THREAD

**Issue by AntonZab** [digital-sound-antiques/in_msx#5]
Grider.mgs. When in info menu in Subsongs section I make the following music. This stop Music

https://drive.google.com/file/d/0B0oEDro3cJx-b1FnSncwbElzODg/view?usp=sharing

P.s In All mgs music same trouble

**Comment by okaxaki** [comment]
Because there is no subsongs in .mgs file. Only .kss can contain multiple songs.
These formats are very very old and there is no enough information on the web. 
I will write FAQ about the formats eventually.
