### ISSUE TITLE
It crash

### ISSUE THREAD

**Issue by Gradius2** [digital-sound-antiques/in_msx#8]
For some reason it crashes:
Winamp client version: 5.8 Build 3660
winamp caused an Access Violation (0xc0000005)
in module in_msx.dll at 0023:6df906e4.

Exception handler called in Winamp.

**Comment by okaxaki** [comment]
Sorry I can not get official distribution of Winamp 5.8 any more.
Please use this with Winamp 5.9 or WACUP.
